version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tvmaze_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/tvmaze_development
      TVMAZE_API_URL: https://api.tvmaze.com/schedule/web
      RAILS_ENV: development
      API_USERNAME: admin
      API_PASSWORD: password123
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"

volumes:
  postgres_data:
  bundle_cache: 